//! Core synthesis abstractions — traits, metrics, RTL generation.
//!
//! Tool-agnostic layer. No backend knows about any specific synthesis tool.
//! All backends live in `synth::backends` and implement only the `RunSynthesis` trait.
//!
//! # Architecture
//!
//! ```text
//! synth::SynthesisMetrics   ← data shared by all backends
//! synth::GenerateRtl        ← spec → RTL file (tool-agnostic)
//! synth::RunSynthesis       ← RTL file → metrics (tool-agnostic trait)
//! synth::SvGenerator        ← default GenerateRtl impl
//! synth::MockSynthesisBackend ← test/CI backend (no external tool)
//! synth::backends::yosys    ← YosysBackend (only backend with external dependency)
//! ```

pub mod backends;

use crate::spec::VerificationSpec;
use serde::{Deserialize, Serialize};

/// Tool-agnostic synthesis metrics.
///
/// Every synthesis backend produces these fields. Backend-specific data
/// (e.g. Yosys cell types, DOT diagram path) goes into `raw` as an
/// opaque JSON object — the core layer does not know about any tool.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SynthesisMetrics {
    pub tool: String,
    pub version: String,
    pub source: String,
    pub module_name: String,
    pub gate_count: Option<u64>,
    pub cell_area: Option<f64>,
    /// Backend-specific opaque data (opaque to core).
    /// YosysBackend populates this with dot_path, cell_types, warnings, etc.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extra: Option<serde_json::Value>,
    pub status: String,
    pub message: Option<String>,
}

impl From<SynthesisMetrics> for crate::fih::Fact {
    fn from(m: SynthesisMetrics) -> Self {
        let origin = format!("ev/synthesis/{}", m.tool);
        let mut payload = serde_json::json!({
            "tool": m.tool,
            "version": m.version,
            "source": m.source,
            "gate_count": m.gate_count,
            "cell_area": m.cell_area,
            "status": m.status,
            "message": m.message,
        });
        if let Some(ref extra) = m.extra {
            payload["extra"] = extra.clone();
        }
        crate::fih::Fact::new("synthesis_result", &origin, &m.module_name, payload)
    }
}

/// Capability: generate RTL source from a verification spec.
///
/// Decoupled from synthesis so any RTL dialect (SystemVerilog, Verilog,
/// VHDL, Chisel) can feed any synthesis backend.
pub trait GenerateRtl: Send + Sync {
    fn generate(&self, spec: &VerificationSpec) -> anyhow::Result<std::path::PathBuf>;
}

/// Capability: run a synthesis tool on an RTL file and produce metrics.
///
/// The tool is invoked with an RTL path and a top-level module name.
/// Backends implement only this trait — they don't know about VerificationSpec.
///
/// # Error contract
///
/// * `Ok(metrics)` — always returned on successful tool execution.
///   Tool-level failures (yosys error, script stderr) are encoded in
///   `metrics.status` as `"error"` and `metrics.message`.
/// * `Err(...)` — returned only for infrastructure failures (file not found,
///   permission denied, JSON parse error).
pub trait RunSynthesis: Send + Sync {
    fn run(&self, rtl_path: &std::path::Path, top_module: &str)
        -> anyhow::Result<SynthesisMetrics>;
}

/// Default RTL generator — produces SystemVerilog.
pub struct SvGenerator;

impl GenerateRtl for SvGenerator {
    fn generate(&self, spec: &VerificationSpec) -> anyhow::Result<std::path::PathBuf> {
        generate_sv(spec)
    }
}

fn generate_sv(spec: &VerificationSpec) -> anyhow::Result<std::path::PathBuf> {
    let tmp_dir = std::env::temp_dir().join("ev-synth");
    std::fs::create_dir_all(&tmp_dir)?;
    let unique_suffix: String = std::iter::repeat_with(fast_random_char).take(8).collect();
    let sv_path = tmp_dir.join(format!("{}_{}.sv", spec.target, unique_suffix));

    if spec.fields.is_empty() {
        anyhow::bail!("Cannot generate SystemVerilog: spec has no fields");
    }

    let mut sv = String::new();
    sv.push_str("// Auto-generated by ev — ExaVerif\n");
    sv.push_str(&format!("module {} (\n", spec.target));

    let field_names: Vec<&String> = spec.fields.keys().collect();
    let mut ports: Vec<String> = Vec::new();
    for name in &field_names {
        let field = &spec.fields[*name];
        let width = field_bit_width(field);
        ports.push(format!(
            "  input logic [{}:0] {}",
            width.saturating_sub(1),
            name
        ));
    }
    let max_field_width = spec.fields.values().map(field_bit_width).max().unwrap_or(1);
    let result_width = max_field_width + (spec.fields.len() as u32).next_power_of_two().ilog2();
    ports.push(format!(
        "  output logic [{}:0] result",
        result_width.saturating_sub(1)
    ));
    sv.push_str(&ports.join(",\n"));
    sv.push_str("\n);\n\n");

    let projector_expr = sv_projector(&spec.projector, &field_names);
    sv.push_str(&format!("  assign result = {};\n", projector_expr));

    for constraint in &spec.constraints {
        sv.push_str(&format!(
            "\n  {}",
            sv_constraint_assertion(constraint, &field_names)
        ));
    }

    sv.push_str("\nendmodule\n");
    std::fs::write(&sv_path, sv)?;
    Ok(sv_path)
}

/// Minimum bit width needed to represent a field's domain.
fn field_bit_width(field: &crate::spec::FieldSpec) -> u32 {
    if let Some(ref values) = field.values {
        if values.is_empty() {
            return 1;
        }
        let max_val = values.iter().max().unwrap_or(&0).unsigned_abs();
        let min_val = values.iter().min().unwrap_or(&0).unsigned_abs();
        let span = max_val.max(min_val);
        return bits_for(span);
    }
    if let Some((min, max)) = field.range {
        let span = (max - min)
            .unsigned_abs()
            .max(max.unsigned_abs())
            .max(min.unsigned_abs());
        return bits_for(span);
    }
    8
}

fn bits_for(value: u64) -> u32 {
    if value == 0 {
        return 1;
    }
    64 - value.leading_zeros()
}

/// Fast non-crypto random char for temp file suffixes.
fn fast_random_char() -> char {
    use std::collections::hash_map::RandomState;
    use std::hash::{BuildHasher, Hasher};
    let h = RandomState::new().build_hasher().finish();
    (b'a' + (h % 26) as u8) as char
}

/// Generate the right-hand side expression for the projector.
fn sv_projector(proj: &crate::spec::ProjectorSpec, field_names: &[&String]) -> String {
    match proj {
        crate::spec::ProjectorSpec::Sum => field_names
            .iter()
            .map(|n| n.as_str())
            .collect::<Vec<_>>()
            .join(" + "),
        crate::spec::ProjectorSpec::Identity { field } => field.clone(),
        crate::spec::ProjectorSpec::Parity { field } => {
            format!("{}[0]", field)
        }
    }
}

/// Generate a SystemVerilog assertion for a constraint.
fn sv_constraint_assertion(
    constraint: &crate::spec::ConstraintSpec,
    _field_names: &[&String],
) -> String {
    match constraint {
        crate::spec::ConstraintSpec::Range { field, min, max } => {
            format!(
                "assert property ({} >= {} && {} <= {}); // range\n",
                field, min, field, max
            )
        }
        crate::spec::ConstraintSpec::Even { field } => {
            format!("assert property ({}[0] == 1'b0); // even\n", field)
        }
        crate::spec::ConstraintSpec::Eq { field_a, field_b } => {
            format!("assert property ({} == {}); // eq\n", field_a, field_b)
        }
        crate::spec::ConstraintSpec::Neq { field_a, field_b } => {
            format!("assert property ({} != {}); // neq\n", field_a, field_b)
        }
        crate::spec::ConstraintSpec::Lt { field, value } => {
            format!("assert property ({} < {}); // lt\n", field, value)
        }
        crate::spec::ConstraintSpec::Gt { field, value } => {
            format!("assert property ({} > {}); // gt\n", field, value)
        }
        crate::spec::ConstraintSpec::Le { field, value } => {
            format!("assert property ({} <= {}); // le\n", field, value)
        }
        crate::spec::ConstraintSpec::Ge { field, value } => {
            format!("assert property ({} >= {}); // ge\n", field, value)
        }
        crate::spec::ConstraintSpec::Oneof { field, values } => {
            let or_exprs: Vec<String> = values
                .iter()
                .map(|v| format!("{} == {}", field, v))
                .collect();
            format!("assert property ({}); // oneof\n", or_exprs.join(" || "))
        }
        crate::spec::ConstraintSpec::Cross {
            field_a,
            field_b,
            mapping,
        } => {
            let name_a = field_a.as_str();
            let name_b = field_b.as_str();
            let assertions: Vec<String> = mapping
                .iter()
                .map(|(va, vbs)| {
                    let set = vbs
                        .iter()
                        .map(|v| v.to_string())
                        .collect::<Vec<_>>()
                        .join(", ");
                    format!(
                        "assert property (({} == {}) -> ({} inside {{{}}})); // cross\n",
                        name_a, va, name_b, set
                    )
                })
                .collect();
            assertions.join("\n  ")
        }
    }
}

/// Synthesis error report helper.
///
/// Produces a `SynthesisMetrics` with `status: "error"` and the given
/// message, using sensible defaults for all other fields.
pub fn error_report(
    tool: &str,
    version: &str,
    source: &std::path::Path,
    module_name: &str,
    message: String,
) -> SynthesisMetrics {
    SynthesisMetrics {
        tool: tool.into(),
        version: version.into(),
        source: source.to_string_lossy().to_string(),
        module_name: module_name.into(),
        gate_count: None,
        cell_area: None,
        extra: None,
        status: "error".into(),
        message: Some(message),
    }
}

// ── Inline MockSynthesisBackend ──────────────────────────────────────
// MockSynthesisBackend is tool-agnostic and lives directly in the core
// layer. Backends with external tool dependencies go into `backends/`.

pub struct MockSynthesisBackend;

impl RunSynthesis for MockSynthesisBackend {
    fn run(
        &self,
        rtl_path: &std::path::Path,
        top_module: &str,
    ) -> anyhow::Result<SynthesisMetrics> {
        let content = std::fs::read_to_string(rtl_path).map_err(|e| {
            anyhow::anyhow!("Mock: cannot read RTL file {}: {}", rtl_path.display(), e)
        })?;

        if !content.contains(&format!("module {}", top_module)) {
            anyhow::bail!(
                "Mock: RTL file {} does not contain module {}",
                rtl_path.display(),
                top_module
            );
        }

        Ok(SynthesisMetrics {
            tool: "mock".into(),
            version: "0.0.0".into(),
            source: rtl_path.to_string_lossy().to_string(),
            module_name: top_module.into(),
            gate_count: Some(0),
            cell_area: None,
            extra: None,
            status: "ok".into(),
            message: None,
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::spec::{ConstraintSpec, FieldSpec, ProjectorSpec, VerificationSpec};
    use std::collections::BTreeMap;

    fn make_spec(
        fields: BTreeMap<String, FieldSpec>,
        projector: ProjectorSpec,
    ) -> VerificationSpec {
        VerificationSpec {
            target: "test_module".into(),
            fields,
            constraints: vec![],
            projector,
        }
    }

    // ── field_bit_width ───────────────────────────────────────────

    #[test]
    fn bit_width_range_0_15() {
        let f = FieldSpec {
            range: Some((0, 15)),
            alignment: None,
            values: None,
        };
        assert_eq!(field_bit_width(&f), 4);
    }

    #[test]
    fn bit_width_range_0_4() {
        let f = FieldSpec {
            range: Some((0, 4)),
            alignment: None,
            values: None,
        };
        assert_eq!(field_bit_width(&f), 3);
    }

    #[test]
    fn bit_width_range_0_0() {
        let f = FieldSpec {
            range: Some((0, 0)),
            alignment: None,
            values: None,
        };
        assert_eq!(field_bit_width(&f), 1);
    }

    #[test]
    fn bit_width_values_single_bit() {
        let f = FieldSpec {
            range: None,
            alignment: None,
            values: Some(vec![0, 1]),
        };
        assert_eq!(field_bit_width(&f), 1);
    }

    #[test]
    fn bit_width_values_three_bits() {
        let f = FieldSpec {
            range: None,
            alignment: None,
            values: Some(vec![0, 3, 7]),
        };
        assert_eq!(field_bit_width(&f), 3);
    }

    #[test]
    fn bit_width_empty_values_defaults_to_1() {
        let f = FieldSpec {
            range: None,
            alignment: None,
            values: Some(vec![]),
        };
        assert_eq!(field_bit_width(&f), 1);
    }

    #[test]
    fn bit_width_defaults_to_8() {
        let f = FieldSpec {
            range: None,
            alignment: None,
            values: None,
        };
        assert_eq!(field_bit_width(&f), 8);
    }

    // ── sv_projector ──────────────────────────────────────────────

    fn names(s: &[&str]) -> Vec<String> {
        s.iter().map(|n| n.to_string()).collect()
    }

    fn name_refs(v: &[String]) -> Vec<&String> {
        v.iter().collect()
    }

    #[test]
    fn projector_sum_two_fields() {
        let n = names(&["a", "b"]);
        let refs = name_refs(&n);
        let expr = sv_projector(&ProjectorSpec::Sum, &refs);
        assert_eq!(expr, "a + b");
    }

    #[test]
    fn projector_sum_single_field() {
        let n = names(&["x"]);
        let refs = name_refs(&n);
        let expr = sv_projector(&ProjectorSpec::Sum, &refs);
        assert_eq!(expr, "x");
    }

    #[test]
    fn projector_identity_field_a() {
        let n = names(&["a", "b"]);
        let refs = name_refs(&n);
        let expr = sv_projector(&ProjectorSpec::Identity { field: "a".into() }, &refs);
        assert_eq!(expr, "a");
    }

    #[test]
    fn projector_identity_field_b() {
        let n = names(&["a", "b"]);
        let refs = name_refs(&n);
        let expr = sv_projector(&ProjectorSpec::Identity { field: "b".into() }, &refs);
        assert_eq!(expr, "b");
    }

    #[test]
    fn projector_identity_with_field_name() {
        let n = names(&["a"]);
        let refs = name_refs(&n);
        let expr = sv_projector(&ProjectorSpec::Identity { field: "a".into() }, &refs);
        assert_eq!(expr, "a");
    }

    #[test]
    fn projector_parity_extracts_lsb() {
        let n = names(&["x"]);
        let refs = name_refs(&n);
        let expr = sv_projector(&ProjectorSpec::Parity { field: "x".into() }, &refs);
        assert_eq!(expr, "x[0]");
    }

    // ── sv_constraint_assertion ───────────────────────────────────

    #[test]
    fn constraint_range() {
        let n = names(&["a"]);
        let refs = name_refs(&n);
        let s = sv_constraint_assertion(
            &ConstraintSpec::Range {
                field: "a".into(),
                min: 0,
                max: 15,
            },
            &refs,
        );
        assert!(s.contains("assert property"));
        assert!(s.contains("a >= 0"));
        assert!(s.contains("a <= 15"));
    }

    #[test]
    fn constraint_even() {
        let n = names(&["x"]);
        let refs = name_refs(&n);
        let s = sv_constraint_assertion(&ConstraintSpec::Even { field: "x".into() }, &refs);
        assert!(s.contains("assert property"));
        assert!(s.contains("x[0] == 1'b0"));
    }

    #[test]
    fn constraint_eq() {
        let n = names(&["a", "b"]);
        let refs = name_refs(&n);
        let s = sv_constraint_assertion(
            &ConstraintSpec::Eq {
                field_a: "a".into(),
                field_b: "b".into(),
            },
            &refs,
        );
        assert!(s.contains("assert property"));
        assert!(s.contains("a == b"));
    }

    // ── New constraint SV assertions ──────────────────────────────

    #[test]
    fn constraint_neq() {
        let n = names(&["a", "b"]);
        let refs = name_refs(&n);
        let s = sv_constraint_assertion(
            &ConstraintSpec::Neq {
                field_a: "a".into(),
                field_b: "b".into(),
            },
            &refs,
        );
        assert!(s.contains("assert property"));
        assert!(s.contains("a != b"));
    }

    #[test]
    fn constraint_gt() {
        let n = names(&["x"]);
        let refs = name_refs(&n);
        let s = sv_constraint_assertion(
            &ConstraintSpec::Gt {
                field: "x".into(),
                value: 100,
            },
            &refs,
        );
        assert!(s.contains("assert property"));
        assert!(s.contains("x > 100"));
    }

    #[test]
    fn constraint_oneof() {
        let n = names(&["op"]);
        let refs = name_refs(&n);
        let s = sv_constraint_assertion(
            &ConstraintSpec::Oneof {
                field: "op".into(),
                values: vec![0, 2, 4],
            },
            &refs,
        );
        assert!(s.contains("assert property"));
        assert!(s.contains("op == 0"));
        assert!(s.contains("op == 2"));
        assert!(s.contains("op == 4"));
        assert!(s.contains("||"));
    }

    // ── generate_sv ───────────────────────────────────────────────

    #[test]
    fn generate_sv_produces_module_header() {
        let mut fields = BTreeMap::new();
        fields.insert(
            "op".into(),
            FieldSpec {
                range: Some((0, 7)),
                alignment: None,
                values: None,
            },
        );
        let spec = make_spec(fields, ProjectorSpec::Identity { field: "op".into() });

        let sv_path = generate_sv(&spec).unwrap();
        let content = std::fs::read_to_string(&sv_path).unwrap();

        assert!(content.contains("module test_module ("));
        assert!(content.contains("input logic [2:0] op"));
        assert!(content.contains("output logic [2:0] result"));
        assert!(content.contains("assign result = op;"));
        assert!(content.contains("endmodule"));
    }

    #[test]
    fn generate_sv_with_constraints() {
        let mut fields = BTreeMap::new();
        fields.insert(
            "a".into(),
            FieldSpec {
                range: Some((0, 15)),
                alignment: None,
                values: None,
            },
        );
        fields.insert(
            "b".into(),
            FieldSpec {
                range: Some((0, 15)),
                alignment: None,
                values: None,
            },
        );
        let mut spec = make_spec(fields, ProjectorSpec::Sum);
        spec.constraints = vec![ConstraintSpec::Eq {
            field_a: "a".into(),
            field_b: "b".into(),
        }];

        let sv_path = generate_sv(&spec).unwrap();
        let content = std::fs::read_to_string(&sv_path).unwrap();

        assert!(content.contains("assign result = a + b;"));
        assert!(content.contains("assert property (a == b);"));
    }

    #[test]
    fn generate_sv_empty_fields_is_error() {
        let spec = make_spec(BTreeMap::new(), ProjectorSpec::Sum);
        let result = generate_sv(&spec);
        assert!(result.is_err());
        assert!(result.unwrap_err().to_string().contains("no fields"));
    }

    #[test]
    fn generate_sv_parity_projector() {
        let mut fields = BTreeMap::new();
        fields.insert(
            "x".into(),
            FieldSpec {
                range: Some((0, 255)),
                alignment: None,
                values: None,
            },
        );
        let spec = make_spec(fields, ProjectorSpec::Parity { field: "x".into() });

        let sv_path = generate_sv(&spec).unwrap();
        let content = std::fs::read_to_string(&sv_path).unwrap();

        assert!(content.contains("assign result = x[0];"));
        assert!(content.contains("input logic [7:0] x"));
    }

    #[test]
    fn generate_sv_with_two_fields_sums_correctly() {
        let mut fields = BTreeMap::new();
        fields.insert(
            "a".into(),
            FieldSpec {
                range: Some((0, 15)),
                alignment: None,
                values: None,
            },
        );
        fields.insert(
            "b".into(),
            FieldSpec {
                range: Some((0, 31)),
                alignment: None,
                values: None,
            },
        );
        let spec = make_spec(fields, ProjectorSpec::Sum);

        let sv_path = generate_sv(&spec).unwrap();
        let content = std::fs::read_to_string(&sv_path).unwrap();

        // a(4bit) + b(5bit) => max=5, len=2, 2.next_power_of_two().ilog2()=1 => result_width=6
        assert!(content.contains("input logic [3:0] a"));
        assert!(content.contains("input logic [4:0] b"));
        assert!(content.contains("output logic [5:0] result"));
    }

    // ── SynthesisMetrics → Fact ────────────────────────────────────

    #[test]
    fn synthesis_metrics_to_fact() {
        let extra = serde_json::json!({
            "dot_path": "/tmp/netlist.dot",
            "cell_types": null,
        });
        let metrics = SynthesisMetrics {
            tool: "yosys".into(),
            version: "0.50".into(),
            source: "/tmp/test.sv".into(),
            module_name: "my_alu".into(),
            gate_count: Some(142),
            cell_area: Some(0.012),
            extra: Some(extra),
            status: "ok".into(),
            message: None,
        };
        let fact: crate::fih::Fact = metrics.into();

        assert_eq!(fact.fact_type, "synthesis_result");
        assert_eq!(fact.origin, "ev/synthesis/yosys");
        assert_eq!(fact.target, "my_alu");
        assert_eq!(fact.payload["tool"], "yosys");
        assert_eq!(fact.payload["gate_count"], 142);
        assert_eq!(fact.payload["extra"]["dot_path"], "/tmp/netlist.dot");
        assert_eq!(fact.payload["status"], "ok");
        assert!(!fact.timestamp.is_empty());
    }

    #[test]
    fn synthesis_metrics_error_to_fact() {
        let metrics = SynthesisMetrics {
            tool: "unknown".into(),
            version: "unknown".into(),
            source: "/tmp/test.sv".into(),
            module_name: "bad_module".into(),
            gate_count: None,
            cell_area: None,
            extra: None,
            status: "error".into(),
            message: Some("yosys not found".into()),
        };
        let fact: crate::fih::Fact = metrics.into();

        assert_eq!(fact.fact_type, "synthesis_result");
        assert_eq!(fact.payload["status"], "error");
        assert_eq!(fact.payload["message"], "yosys not found");
        assert!(fact.payload["gate_count"].is_null());
    }

    // ── MockSynthesisBackend ───────────────────────────────────────

    #[test]
    fn mock_backend_valid_sv() {
        let mut fields = BTreeMap::new();
        fields.insert(
            "a".into(),
            FieldSpec {
                range: Some((0, 7)),
                alignment: None,
                values: None,
            },
        );
        let spec = make_spec(fields, ProjectorSpec::Identity { field: "a".into() });
        let rtl_path = SvGenerator.generate(&spec).unwrap();

        let metrics = MockSynthesisBackend.run(&rtl_path, "test_module").unwrap();
        assert_eq!(metrics.tool, "mock");
        assert_eq!(metrics.status, "ok");
        assert_eq!(metrics.gate_count, Some(0));
    }

    #[test]
    fn mock_backend_wrong_module_name() {
        let mut fields = BTreeMap::new();
        fields.insert(
            "a".into(),
            FieldSpec {
                range: Some((0, 7)),
                alignment: None,
                values: None,
            },
        );
        let spec = make_spec(fields, ProjectorSpec::Identity { field: "a".into() });
        let rtl_path = SvGenerator.generate(&spec).unwrap();

        let result = MockSynthesisBackend.run(&rtl_path, "nonexistent_module");
        assert!(result.is_err());
    }

    #[test]
    fn mock_backend_missing_file() {
        let result =
            MockSynthesisBackend.run(std::path::Path::new("/tmp/ev-nonexistent.sv"), "foo");
        assert!(result.is_err());
    }

    #[test]
    fn full_pipeline_with_mock() {
        let mut fields = BTreeMap::new();
        fields.insert(
            "x".into(),
            FieldSpec {
                range: Some((0, 3)),
                alignment: None,
                values: None,
            },
        );
        let spec = make_spec(fields, ProjectorSpec::Sum);

        let rtl_path = SvGenerator.generate(&spec).unwrap();
        let metrics = MockSynthesisBackend.run(&rtl_path, "test_module").unwrap();

        assert_eq!(metrics.module_name, "test_module");
        assert_eq!(metrics.status, "ok");
    }
}
