//! Synthesis capability — runs external synthesis tools and produces reports.
//!
//! Each backend implements the `SynthesisCapable` trait. The pipeline depends
//! on the trait, not on any specific tool.

use crate::spec::VerificationSpec;
use serde::{Deserialize, Serialize};

/// Report produced by a synthesis backend.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SynthesisReport {
    pub tool: String,
    pub version: String,
    pub source: String,
    pub module_name: String,
    pub gate_count: Option<u64>,
    pub cell_area: Option<f64>,
    pub status: String,
    pub message: Option<String>,
}

/// Capability: synthesize a design from a verification spec.
pub trait SynthesisCapable: Send + Sync {
    fn synthesize(&self, spec: &VerificationSpec) -> anyhow::Result<SynthesisReport>;
}

/// Backend that runs an external shell script.
pub struct ScriptBackend {
    script_path: std::path::PathBuf,
}

impl ScriptBackend {
    pub fn new(script_path: std::path::PathBuf) -> Self {
        Self { script_path }
    }
}

impl SynthesisCapable for ScriptBackend {
    fn synthesize(&self, spec: &VerificationSpec) -> anyhow::Result<SynthesisReport> {
        let sv_path = generate_sv(spec)?;
        let output = std::process::Command::new("bash")
            .arg(&self.script_path)
            .arg(&sv_path)
            .arg(&spec.target)
            .output()
            .map_err(|e| anyhow::anyhow!("Failed to run synthesis: {}", e))?;

        if !output.status.success() {
            let stderr = String::from_utf8_lossy(&output.stderr);
            return Ok(SynthesisReport {
                tool: "unknown".into(),
                version: "unknown".into(),
                source: sv_path.to_string_lossy().to_string(),
                module_name: spec.target.clone(),
                gate_count: None,
                cell_area: None,
                status: "error".into(),
                message: Some(stderr.to_string()),
            });
        }

        let stdout = String::from_utf8_lossy(&output.stdout);
        let report: SynthesisReport = serde_json::from_str(&stdout)
            .map_err(|e| anyhow::anyhow!("Failed to parse synthesis JSON: {}", e))?;
        Ok(report)
    }
}

fn generate_sv(spec: &VerificationSpec) -> anyhow::Result<std::path::PathBuf> {
    let tmp_dir = std::env::temp_dir().join("ev-synth");
    std::fs::create_dir_all(&tmp_dir)?;
    let sv_path = tmp_dir.join(format!("{}.sv", spec.target));
    let mut sv = String::new();
    sv.push_str("// Auto-generated by ev — ExaVerif\n");
    sv.push_str(&format!("module {} (\n", spec.target));

    // Port declarations — one input per field, plus a result output.
    let field_names: Vec<&String> = spec.fields.keys().collect();
    let mut ports: Vec<String> = Vec::new();
    for name in &field_names {
        let field = &spec.fields[*name];
        let width = field_bit_width(field);
        ports.push(format!("  input logic [{}:0] {}", width.saturating_sub(1), name));
    }
    // Result width: generous ceiling based on field count and max width.
    let max_field_width = spec.fields.values().map(|f| field_bit_width(f)).max().unwrap_or(1);
    let result_width = max_field_width + (spec.fields.len() as u32).next_power_of_two().ilog2();
    ports.push(format!("  output logic [{}:0] result", result_width.saturating_sub(1)));
    sv.push_str(&ports.join(",\n"));
    sv.push_str("\n);\n\n");

    // Projector logic.
    let projector_expr = sv_projector(&spec.projector, &field_names);
    sv.push_str(&format!("  assign result = {};\n", projector_expr));

    // Constraint assertions.
    for constraint in &spec.constraints {
        sv.push_str(&format!("\n  {}", sv_constraint_assertion(constraint, &field_names)));
    }

    sv.push_str("\nendmodule\n");
    std::fs::write(&sv_path, sv)?;
    Ok(sv_path)
}

/// Minimum bit width needed to represent a field's domain.
fn field_bit_width(field: &crate::spec::FieldSpec) -> u32 {
    if let Some(ref values) = field.values {
        if values.is_empty() {
            return 1;
        }
        let max_val = values.iter().max().unwrap_or(&0).unsigned_abs();
        let min_val = values.iter().min().unwrap_or(&0).unsigned_abs();
        let span = max_val.max(min_val);
        return bits_for(span);
    }
    if let Some((min, max)) = field.range {
        let span = (max - min).unsigned_abs().max(max.unsigned_abs()).max(min.unsigned_abs());
        return bits_for(span);
    }
    8 // default
}

fn bits_for(value: u64) -> u32 {
    if value == 0 {
        return 1;
    }
    64 - value.leading_zeros()
}

/// Generate the right-hand side expression for the projector.
fn sv_projector(proj: &crate::spec::ProjectorSpec, field_names: &[&String]) -> String {
    match proj {
        crate::spec::ProjectorSpec::Sum => {
            field_names.iter().map(|n| n.as_str()).collect::<Vec<_>>().join(" + ")
        }
        crate::spec::ProjectorSpec::Identity { axis } => {
            field_names.get(*axis).map(|n| n.as_str()).unwrap_or("0").to_string()
        }
        crate::spec::ProjectorSpec::Parity { axis } => {
            let name = field_names.get(*axis).map(|n| n.as_str()).unwrap_or("0");
            format!("{}[0]", name)
        }
    }
}

/// Generate a SystemVerilog assertion for a constraint.
fn sv_constraint_assertion(
    constraint: &crate::spec::ConstraintSpec,
    field_names: &[&String],
) -> String {
    match constraint {
        crate::spec::ConstraintSpec::Range { axis, min, max } => {
            let name = field_names.get(*axis).map(|n| n.as_str()).unwrap_or("0");
            format!(
                "assert property ({} >= {} && {} <= {}); // range\n",
                name, min, name, max
            )
        }
        crate::spec::ConstraintSpec::Even { axis } => {
            let name = field_names.get(*axis).map(|n| n.as_str()).unwrap_or("0");
            format!("assert property ({}[0] == 1'b0); // even\n", name)
        }
        crate::spec::ConstraintSpec::Eq { axis_a, axis_b } => {
            let name_a = field_names.get(*axis_a).map(|n| n.as_str()).unwrap_or("0");
            let name_b = field_names.get(*axis_b).map(|n| n.as_str()).unwrap_or("0");
            format!("assert property ({} == {}); // eq\n", name_a, name_b)
        }
    }
}

/// Run the default synthesis backend.
pub fn synthesize_default(spec: &VerificationSpec) -> anyhow::Result<SynthesisReport> {
    let script_path = if let Ok(path) = std::env::var("EV_SYNTH_SCRIPT") {
        std::path::PathBuf::from(path)
    } else {
        let candidates = [
            std::env::current_exe().ok().and_then(|p| {
                p.parent().map(|p| p.join("../scripts/synth/default-synth.sh"))
            }),
            Some(std::path::PathBuf::from("scripts/synth/default-synth.sh")),
        ];
        let mut found = None;
        for c in candidates.iter().flatten() {
            if c.exists() {
                found = Some(c.clone());
                break;
            }
        }
        found.ok_or_else(|| {
            anyhow::anyhow!(
                "No synthesis script. Set EV_SYNTH_SCRIPT or install \
                 scripts/synth/default-synth.sh"
            )
        })?
    };
    ScriptBackend::new(script_path).synthesize(spec)
}
